/**
 * Turning the service worker on.
 *
 * Production only. In development Vite serves modules that are rewritten on every
 * change, and a worker holding a cache of them in front of that is a morning spent
 * wondering why an edit did nothing. `sw.js` is generated by the build — see the
 * plugin in `vite.config.ts` — so there is nothing at that path to register in dev
 * anyway.
 */

export function registerServiceWorker(): void {
	if (!import.meta.env.PROD) return
	if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return

	// After load, not during it: registering pulls the whole precache down, and none of
	// it should be competing with the page the reader is waiting for.
	window.addEventListener('load', () => {
		navigator.serviceWorker.register('/sw.js').catch(() => {
			// No offline mode, then. Nothing else about the site depends on it — the
			// queue is IndexedDB and works in a tab that is already open either way.
		})
	})
}

/**
 * True when a service worker is answering for this page.
 *
 * Which is to say: whether a full page load would survive being offline. The create
 * page asks before deciding how to leave itself after an offline save — see
 * `CreatePage`.
 */
export function hasServiceWorker(): boolean {
	return typeof navigator !== 'undefined' && navigator.serviceWorker?.controller != null
}
